# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx6G

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.18.1

# Mod Properties
mod_version=3.3.3
maven_group=moe.seikimo
archives_base_name=mwhrd

# Dependencies
fabric_version=0.138.3+1.21.10
sgui_version=1.10.2+1.21.8
geyser_version=2.9.1-SNAPSHOT
polymer_version=0.14.3+1.21.10
translations_version=2.5.2+1.21.9-pre3
fantasy_version=0.6.8+1.21.9

lombok_version=1.18.32
mongo_version=1.45.0
morphia_version=2.1.7

# Build-time constants
server_name=a Minecraft Server

# Endpoints
botw_download=
