# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx6G

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.17.0

# Mod Properties
mod_version=3.3.2
maven_group=moe.seikimo
archives_base_name=mwhrd

# Dependencies
fabric_version=0.130.0+1.21.8
sgui_version=1.10.2+1.21.8
geyser_version=2.8.2-SNAPSHOT
polymer_version=0.13.8+1.21.8
translations_version=2.5.1+1.21.5
fantasy_version=0.6.7+1.21.5

lombok_version=1.18.32
mongo_version=1.45.0
morphia_version=2.1.7

# Build-time constants
server_name=a Minecraft Server

# Endpoints
botw_download=
