# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx6G

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.5
yarn_mappings=1.21.5+build.1
loader_version=0.16.14

# Mod Properties
mod_version=3.3.1
maven_group=moe.seikimo
archives_base_name=mwhrd

# Dependencies
fabric_version=0.121.0+1.21.5
sgui_version=1.9.0+1.21.5
geyser_version=2.7.0-SNAPSHOT
polymer_version=0.12.3+1.21.5
translations_version=2.5.0+1.21.5-rc1
fantasy_version=0.6.7+1.21.5

lombok_version=1.18.32
mongo_version=1.45.0
morphia_version=2.1.7

# Build-time constants
server_name=a Minecraft Server

# Endpoints
botw_download=
